config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, only: :index
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    return if params[:query].blank?

    ingredients = params[:query].split(',').map(&:strip)
    query = ingredients.map { |ingredient| { match_phrase: { ingredients: ingredient } } }
    body = { query: { bool: { should: query } },
             fields: %w[title ingredients ratings],
             _source: false,
             sort: ['_score', { ratings: 'desc' }],
             size: 10 }
    result = ElasticsearchClient.search(index: 'recipes', body:)
    @recipes_hashes = result.dig('hits', 'hits').pluck('fields').map(&:deep_symbolize_keys)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticsearchRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= form_tag(recipes_path, method: :get) do %>
  <%= text_field_tag(:query, params[:query], placeholder: 'Enter list of comma-separated ingredients that you have', size: 100) %>
  <%= submit_tag('Find recipes') %>
<% end %>

<% if @recipes_hashes.present? %>
  <% @recipes_hashes.each do |recipe| %>
    <div>
      <h1> <%= recipe[:title] %> </h1>
      <p> <%= recipe[:ratings] %> </p>
      <p> <%= recipe[:ingredients] %> </p>
    </div>
  <% end %>
<% else %>
  <p> No recipes found for provided ingredients</p>
<% end %>